name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: clinic_user
          POSTGRES_PASSWORD: clinic_password
          POSTGRES_DB: clinic_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://clinic_user:clinic_password@localhost:5432/clinic_db
      PYTHONPATH: /app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and test in Docker
      run: |
        docker build -t my-app .
        docker run --network host -e DATABASE_URL=$DATABASE_URL my-app pytest