name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Pin to Ubuntu 22.04 for stability

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: clinic_user
          POSTGRES_PASSWORD: clinic_password
          POSTGRES_DB: clinic_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://clinic_user:clinic_password@localhost:5432/clinic_db

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use Python 3.10 to avoid C API issues

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev gcc libffi-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==23.11.0 isort==5.12.0 flake8==6.1.0 pytest==7.4.3
        if [ -f requirements.txt ]; then pip install -r requirements.txt --only-binary :all:; else echo "requirements.txt not found"; fi

    - name: Lint code
      run: |
        black --check .
        isort --check-only --diff .
        flake8 .

    - name: Run tests
      run: pytest